@baseUrl = http://localhost:3000

### 1. AppController (GET - Hello)

# @name getHello

GET {{baseUrl}}/home/hello

### 2. AppController (GET - Greeting)

# @name getGreeting

GET {{baseUrl}}/home/greeting

### 3. ConceptsManualController (GET - Concepts Manual)

# @name getConceptsManual

GET {{baseUrl}}/concepts-manual

### 4. ConceptsAutoController (GET - Concepts Auto)

# @name getConceptsAuto

GET {{baseUrl}}/concepts-auto