@baseUrl = http://localhost:3000

### AppController

# @name getHello

GET {{baseUrl}}/home/hello

# @name getGreeting

GET {{baseUrl}}/home/greeting

### ConceptsManualController

# @name getConceptsManual

GET {{baseUrl}}/concepts-manual

### ConceptsAutoController

# @name getConceptsAuto

GET {{baseUrl}}/concepts-auto